*** Settings ***
Documentation  Variable for List of projects
Resource  resource.robot

*** Variables ***
${LIST_OF_PROJECTS_NEW_PROJECT_BUTTON}
${LIST_OF_PROJECTS_ALL_PROJECT_LINK}
${LIST_OF_PROJECTS_DRAFT_LINK}
${LIST_OF_PROJECTS_ON_GOING_LINK}
#
${LIST_OF_PROJECTS_PROJECT_NAME_COLUMN}
${LIST_OF_PROJECTS_TYPE_COLUMN}
${LIST_OF_PROJECTS_STATUS_COLUMN}
${LIST_OF_PROJECTS_RESPONSES_COLUMN}
${LIST_OF_PROJECTS_LAST_MODIFIED_COLUMN}
${LIST_OF_PROJECTS_DUE_DATE_COLUMN}
#
${LIST_OF_PROJECTS_PROJECT_NAME_VALUE}
${LIST_OF_PROJECTS_TYPE_COLUMN_VALUE}
${LIST_OF_PROJECTS_STATUS_COLUMN_VALUE}
${LIST_OF_PROJECTS_RESPONSES_COLUMN_VALUE}
${LIST_OF_PROJECTS_LAST_MODIFIED_COLUMN_VALUE}
${LIST_OF_PROJECTS_DUE_DATE_COLUMN_VALUE}
#
${LIST_OF_PROJECTS_PREV_BUTTON}
${LIST_OF_PROJECTS_NEXT_BUTTON}
${LIST_OF_PROJECTS_PAGING_BUTTON}
#EDIT PROJECT MENU
${LIST_OF_PROJECTS_EDIT_BUTTON}
${LIST_OF_PROJECTS_EDIT_RENAME_BUTTON}
${LIST_OF_PROJECTS_EDIT_DUPLICATE_BUTTON}
${LIST_OF_PROJECTS_EDIT_EDIT_PROJECT_BUTTON}
${LIST_OF_PROJECTS_EDIT_PREVIEW_RENAME_BUTTON}
${LIST_OF_PROJECTS_EDIT_DELETE_PROJECT_BUTTON}
